Repository broadinstitute/gatk-sv, pull requests merged in 2024-09, with the labels that each got.

#716 Rename high & low overall outliers columns generated via EvidenceQC
  src/sv-pipeline/scripts/make_evidence_qc_table.py
Labels: enhancement

#725 Include SVTK documentation in README
  src/svtk/README.md
Labels: documentation

#711 Deprecate Google Cloud configuration JSONs
  .github/workflows/testwdls.yaml
  README.md
  inputs/values/google_cloud.json
  scripts/cromwell/launch_wdl.sh
  scripts/inputs/build_default_inputs.sh
  scripts/inputs/build_inputs.py
  website/docs/advanced/build_inputs.md
  website/docs/gs/quick_start.md
Labels: enhancement

#727 Update type-checking in RdTestV2 to be class-based
  src/RdTest/RdTestV2.R
Labels: enhancement

#708 Resolve incorrect mCNV genotype counts for hom-alt
  src/sv-pipeline/scripts/vcf_qc/collectQC.vcf_wide.sh
Labels: bug

#681 Update GatherSampleEvidence & TrainGCNV docs
  website/docs/gs/runtime_env.md
  website/docs/modules/evidence_qc.md
  website/docs/modules/gather_batch_evidence.md
  website/docs/modules/gather_sample_evidence.md
  website/docs/modules/index.md
  website/docs/modules/train_gcnv.md
  website/src/components/highlight.js
  website/src/css/custom.css
Labels: documentation
