Repository broadinstitute/gatk-sv, pull requests merged in 2025-01, with the labels that each got.

#754 Fix bug that results in an empty Vapor report
  src/sv_utils/src/sv_utils/report_confident_irs_vapor_variants.py
Labels: bug

#744 Create SampleQC and Batching notebooks
  scripts/notebooks/Batching.ipynb
  scripts/notebooks/SampleQC.ipynb
Labels: enhancement

#767 Reorder PED file columns in SampleQC notebook
  scripts/notebooks/SampleQC.ipynb
Labels: bug

#770 Update gatk docker on azure
  inputs/values/dockers_azure.json
Labels: docker
